site_name: PARC FR3 Software Documentation
site_description: Central documentation for FR3 robot software, experiment GUIs, setup, and operations.
site_author: PARC / Arquilla Research Group
repo_name: ulubilgeulusoy/PARC-FR3-Software-Docs
repo_url: https://github.com/ulubilgeulusoy/PARC-FR3-Software-Docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting Started:
      - Sections:
          - Quick Start: getting-started/quick-start.md
          - PARC FR3 Capabilitites: getting-started/parc-fr3-capabilities.md
          - Capability Basics: getting-started/capability-basics.md
          - Safety: getting-started/safety.md
  - FR3 Control System Installation Guide:
      - Sections:
          - Summary: installation-guide/summary.md
          - Before Installation: installation-guide/before-installation.md
          - Recommended Installation Steps: installation-guide/recommended-installation-steps.md
          - Lessons Learned: installation-guide/lessons-learned.md
  - FR3 User Guide:
      - Sections:
          - Summary: user-guide/summary/fr3-user-guide-summary.md
          - Read Before Proceed: user-guide/basics/read-before-proceed.md
          - Computers: user-guide/basics/computers.md
          - FR3 Basics: user-guide/basics/fr3-basics.md
          - FR3 Start-up Checklist: user-guide/checklist/fr3-start-up-checklist.md
          - FR3 Example Capabilities:
              - Summary: user-guide/fr3-example-capabilities/summary.md
              - libfranka Examples: user-guide/fr3-example-capabilities/libfranka-examples.md
              - Kinesthetic Teaching: user-guide/fr3-example-capabilities/kinesthetic-teaching.md
              - Visual Servoing: user-guide/fr3-example-capabilities/visual-servoing.md
          - FR3 Non-Remote Control: user-guide/control/fr3-non-remote-control.md
          - FR3 Remote Control: user-guide/control/fr3-remote-control.md
  - Appendix:
      - Sections:
          - Glossary: appendix/glossary.md
